### ISSUE TITLE
DB Modeling of `CommentPath` - Draft 

### ISSUE THREAD

**Issue by gazzua** [marmoym/marmoym-api#206]

**Comment by givem2some** [comment]
## Spec (Update Nov 25, 2017)
- **Marmoym** 에 publishing 되는 컨텐츠는 크게 두 가지 이다: `article`, `comment`. e.g. `article`의 예는 `definition` 이 있다.  
- `parent_id`는 부모 댓글의 id이다. 즉, `comment` 의 식별자를 그 값으로 취한다.
- `target_type`는 `article`의 타입이다. (e.g. `Definition` = `D`)
- `target_id`는 `article`의 식별자이다.
- `depth`는 댓글 깊이를 나타낸다.

### Properties
- id
- gparent_id
- parent_id
- depth
- target_type
- target_id 
- label
- user_id
- vote_id
- status

**Comment by enginehenryed** [comment]
We could still use JSON as format

**Comment by eldeni** [comment]
```json
{
   "1":{
      "2": 0,
      "3":{
         "4": 0
      }
   }
}
```

**Comment by eldeni** [comment]
Done by #215
