### ISSUE TITLE
Ditch Mocha + Chai for Jasmine as testing library

### ISSUE THREAD

**Issue by eldeni** [marmoym/marmoym-api#44]
The reason being that Jasmine has built in assertion methods and mocking functionalities.
The test is going to be needed as functionalities are becoming concrete. e.g. User functionalities.

**Comment by enginehenryed** [comment]
Difference
https://marcofranssen.nl/jasmine-vs-mocha/

Jasmine with TypeScript
https://blog.tonysneed.com/2016/02/27/visual-studio-code-typescript-part-2/

**Comment by gimochi** [comment]
https://github.com/karma-runner/karma-jasmine

**Comment by enginehenryed** [comment]
just a wrapper for jasmine?

**Comment by gimochi** [comment]
ㅇㅇ, 그냥 자료조사중

**Comment by eldeni** [comment]
Mocha will still be used. Closing.
