### ISSUE TITLE
DB Modeling of `Term` - Draft

### ISSUE THREAD

**Issue by eldeni** [marmoym/marmoym-api#54]
# This is INVALID. See the comment below 
https://github.com/tymsai/marmoym-api/issues/54#issuecomment-323582339
- 'Term' is a concept that is a unit in the list of dictionary.
- 'Term' is materialized as 'TermEntry' (This can be named up to the designer)
- 'TermEntry*' has only one Definition, here DefinitionEntry does not have to exist, since all Definition on its own is discrete.

```
Term e.g. "실화니", "실화냐", "실화에요?" ...
TermEntry e.g. {Term: 실화니, Def: "foo"}, {Term: 실화니, Def: "bar"}
Definition e.g. "foo", "bar" ...
```

**Comment by jcooky** [comment]
TermEntry는 table로써는 존재하되 entity로써는 존재하지 않는건가요? 현재 본문에는 두 Entity사이의 연결고리로써만 보입니다.

**Comment by enginehenryed** [comment]
## Update
This will contain the specification. Actual implementation may vary, which is up to the engineer.

-  default: mandatory field 
- *: 0 or more
- +: 1 or more

### Term
Entry in the dictionary. This has to be unique. Also could be named as _word_. 고유한 사전의 표제어

Two different terms can never be the same.
e.g. 
If a.termId != b.termId, 
then a.termValue != b.termValue

#### properties
- id
- val

### Definition
The most important unit, and one of the entities of Marmoym.

#### properties
- id
- val
- pos* (Part of speech, 품사)
- usage+
- img*

**Comment by enginehenryed** [comment]
All the members should take a look. @tymsai/tymsai

**Comment by jcooky** [comment]
label을 너무 많이 남발한거 같습니다. label이 본래의 의도대로 사용할 수 있게 해주십시오.
Term과 Definition간의 관계가 없는 것 같습니다. 해당 관계를 추가해주십시오.

**Comment by enginehenryed** [comment]
@jcooky 
label을 갖는 entity: `term`, `definition`, `pos`, `usage`
예로 `graphicDescription` 은 label이 아니라 url을 필드로 가집니다. 모든 entity가 label을 가지고 있지는 않습니다.

definition - term 관계 추가했습니다.

**Comment by enginehenryed** [comment]
Soon this specification will be moved into _wiki_ of this repository as the discussion has covered quite a lot.

**Comment by eldeni** [comment]
will be archived. closing
