### ISSUE TITLE
Research on which binding library to use for future use of Apache Spark and for batch-processing

### ISSUE THREAD

**Issue by jcooky** [marmoym/marmoym-api#62]
Javascript로 되어있는 현재 서버 아키텍처에서 Apache Spark를 배치 프레임웍으로 쓸 수 있을지 검토가 필요하다.

## Thirdparty
- [eclairjs](https://github.com/EclairJS/eclairjs)
  - Java8에 추가된 nashron 자바스크립트 엔진을 기반으로 Apache Spark의 Task를 작성할 수 있는 라이브러리

**Comment by enginehenryed** [comment]
Renamed for clarification

**Comment by eldeni** [comment]
Closing. will be handled in different issues later.
