### ISSUE TITLE
Research on 'search' optimization, with investigation on Elastic Search and Gimci.js

### ISSUE THREAD

**Issue by jcooky** [marmoym/marmoym-api#63]
나중에 gimci를 활용하여 검색할 수 있는 방법에 대해서 고민해봐야한다. 현재로써 ElasticSearch를 활용하려고 하나 이 프레임웍이 gimci나 우리의 검색 요구사항과 맞을지에 대해서 검토가 필요하다.

이를 위해 ORM을 기반으로 한 Entity들이 ElasticSearch의 Document로 활용가능하도록 설계에 고안되어야한다.

## References
- [ElasticSearch](https://www.elastic.co/products/elasticsearch)
- [ElasticSearch ORM for Node.js](https://github.com/jeresig/elasticsearch-orm)

**Comment by enginehenryed** [comment]
good thought indeed

**Comment by eldeni** [comment]
Closing. will be handled in different issues.
