### ISSUE TITLE
Need CRUD of a comment

### ISSUE THREAD

**Issue by jcooky** [marmoym/marmoym-api#82]

**Comment by gimochi** [comment]
#### comment ids 획득
GET /api/v1/comments/ids?targetType=:targetType&targetId=:targetId
`/api/v1/comments/ids?targetType=D&targetId=1`

#### get comment detail by ids
POST /api/v1/comments
`/api/v1/comments`

#### update comment
PUT /api/v1/comments
`/api/v1/comments`

#### delete comment
DELETE /api/v1/comments
`/api/v1/comments`

#### register comment
POST /api/v1/comments/newComment
`/api/v1/comments/newComment`

**Comment by enginehenryed** [comment]
Needs an updated specification.

**Comment by eldeni** [comment]
Will be handled in different issue. Closing
